name: CI / Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name != 'master' && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  required:
    name: Required Checks
    runs-on: ubuntu-latest
    if: always() # Always run to determine status of upstream jobs
    needs:
      - build
      - integration-test
      - lint
      - test

    steps:
      - id: status
        name: Determine status
        if: always()
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')

          echo "Upstream results: $results"

          if echo "$results" | grep -qE '(failure|cancelled|skipped)'; then
            result="failed"
          else
            result="success"
          fi

          echo "result=$result" >> $GITHUB_OUTPUT
          echo "results=$results" >> $GITHUB_OUTPUT

      - if: steps.status.outputs.result != 'success'
        name: Fail if any upstream failed
        run: |
          echo "One or more upstream jobs failed: ${{ steps.status.outputs.results }}"
          exit 1

  build:
    name: Build - Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --workspace --all-targets

  lint:
    name: Lint, Format and Docs - Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Check Docs
        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --document-private-items

  test:
    name: Test - Crate
    runs-on: ubuntu-latest
    needs: find-crates
    strategy:
      matrix:
        crate: ${{ fromJSON(needs.find-crates.outputs.crates) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.crate }} tests
        run: cargo test -p ${{ matrix.crate }}

  integration-test:
    name: Integration Test - Crate
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --workspace --all-targets --release

        # FIXME: This timeout should be replaced with either something in the test itself
        #  or something within the solver.
      - name: Run integration tests
        run: timeout 240s cargo test --workspace --test tests -- --nocapture

  find-crates:
    name: Discover Crates
    runs-on: ubuntu-latest
    outputs:
      crates: ${{ steps.list-crates.outputs.crates }}
    steps:
      - uses: actions/checkout@v4
      - id: list-crates
        run: |
          crates=$(find crates -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n")[:-1]')
          echo "crates=$crates" >> $GITHUB_OUTPUT
